name: Publish Trackers Pre-Releases to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.rc[0-9]+"
  workflow_dispatch:
  pull_request:
    branches: ['release/*', 'develop']
    paths:
      - '.github/workflows/build-package.yml'
      - '.github/workflows/publish-pre-release.yml'

permissions: {} # Explicitly remove all permissions by default

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-package.yml

  publish-pre-release:
    name: Publish Pre-release Package
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://pypi.org/project/trackers/
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
      contents: read # Required for checkout
    steps:
      - name: ðŸ“¥ Download distribution artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist/
      - name: List distribution artifacts
        run: ls -lh dist/

      - name: ðŸš€ Publish to PyPi
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0  # v1.13.0
        with:
          attestations: true
