name: Publish Trackers Releases to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  pull_request:
    branches: [main, 'release/*']
    paths:
      - '.github/workflows/build-package.yml'
      - '.github/workflows/publish-release.yml'

permissions: {} # Explicitly remove all permissions by default

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-package.yml

  publish-release:
    name: Publish Release Package
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/trackers/
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
      contents: read # Required for checkout
    steps:
      - name: ðŸ“¥ Download distribution artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist/
      - name: List distribution artifacts
        run: ls -lh dist/

      - name: ðŸš€ Publish to PyPi
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          attestations: true
